# Generated by Django 4.2.2 on 2023-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='starting_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
